#!/bin/sh
set -e

case "$1" in
    configure)
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload >/dev/null 2>&1 || true
            systemctl enable magitrickle.service >/dev/null 2>&1 || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
