#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if [ -d /run/systemd/system ]; then
            systemctl disable magitrickle.service >/dev/null 2>&1 || true
            systemctl stop magitrickle.service >/dev/null 2>&1 || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
